<?php

/**
 * @file
 * AURA Sections custom module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function aura_sections_theme() {
  return [
    'aura_hero' => [
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'button_text' => NULL,
        'button_link' => NULL,
        'background_video' => NULL,
        'foreground_image' => NULL,
        'pattern_image' => NULL,
      ],
      'template' => 'block--hero',
      'path' => \Drupal::service('extension.list.module')->getPath('aura_sections') . '/templates',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_block_alter().
 */
function aura_sections_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['#block']) && $variables['elements']['#block'] instanceof \Drupal\Core\Block\BlockPluginInterface) {
    $block = $variables['elements']['#block'];
    $block_id = $block->getPluginId();
    if ($block_id === 'aura_theme_comhofem') {
      $suggestions[] = 'block__aura_theme_comhofem';
    }
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function aura_sections_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  if ($route_match->getRouteName() !== 'entity.node.canonical') {
    return;
  }

  $node = $route_match->getParameter('node');
  if (!$node instanceof \Drupal\node\NodeInterface || $node->bundle() !== 'article') {
    return;
  }

  $has_blog_link = FALSE;
  foreach ($breadcrumb->getLinks() as $link) {
    if ($link->getUrl()->isRouted() && $link->getUrl()->getRouteName() === 'view.blog.page_1') {
      $link->setText('Blog');
      $has_blog_link = TRUE;
    }
  }

  if ($has_blog_link) {
    $breadcrumb->addCacheContexts(['route']);
    $breadcrumb->addCacheableDependency($node);
    return;
  }

  $blog_link = Link::fromTextAndUrl('Blog', Url::fromRoute('view.blog.page_1'));
  $breadcrumb->addLink($blog_link);
  $breadcrumb->addCacheContexts(['route']);
  $breadcrumb->addCacheableDependency($node);
}
