<?php

/**
 * @file
 * AURA Sections custom module.
 */

/**
 * Implements hook_theme().
 */
function aura_sections_theme() {
  return [
    'aura_hero' => [
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'button_text' => NULL,
        'button_link' => NULL,
        'background_video' => NULL,
        'foreground_image' => NULL,
        'pattern_image' => NULL,
      ],
      'template' => 'block--hero',
      'path' => \Drupal::service('extension.list.module')->getPath('aura_sections') . '/templates',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_block_alter().
 */
function aura_sections_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['#block']) && $variables['elements']['#block'] instanceof \Drupal\Core\Block\BlockPluginInterface) {
    $block = $variables['elements']['#block'];
    $block_id = $block->getPluginId();
    if ($block_id === 'aura_theme_comhofem') {
      $suggestions[] = 'block__aura_theme_comhofem';
    }
  }
}
